# Generated by Django 5.1.3 on 2025-05-04 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='up_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eduklinikapp.staff'),
        ),
    ]
