# Generated by Django 5.1.3 on 2025-05-01 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='weeks',
            field=models.CharField(default='1 week', max_length=200, verbose_name='specify how long it should take to complete the course'),
        ),
    ]
