# Generated by Django 5.1.3 on 2025-05-04 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0002_alter_course_up_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile pics', verbose_name='user image')),
                ('is_edit', models.BooleanField(default=False, verbose_name='is edited')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='course',
            name='up_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eduklinikapp.staff'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eduklinikapp.pro_image'),
        ),
        migrations.DeleteModel(
            name='userimage',
        ),
    ]
