# Generated by Django 5.1.3 on 2025-05-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0002_course_weeks'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='c_img',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='add a image to decribe the corse'),
        ),
    ]
