# Generated by Django 5.1.3 on 2025-05-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0003_course_c_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='c_img',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='add a image to decribe the corse'),
        ),
    ]
