# Generated by Django 5.1.3 on 2025-05-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0003_pro_image_remove_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='file_package',
            field=models.FileField(blank=True, null=True, upload_to='lesson files', verbose_name='lesson file package'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='class_level',
            field=models.CharField(blank=True, choices=[('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('BECE', 'BECE'), ('Common entrance', 'Common entrance')], default='Basic6', max_length=200, verbose_name='leasson class'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Tutor', 'Tutor'), ('Contributor', 'Contributor'), ('Developer', 'Developer')], default='Teachers', max_length=200, verbose_name='the staff type'),
        ),
    ]
