# Generated by Django 5.1.3 on 2025-05-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0004_lesson_file_package_alter_lesson_class_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='attribute',
            field=models.CharField(choices=[('lesson note', 'lesson note'), ('past question', 'past question'), ('syllabue', 'syllabue'), ('textbook', 'textbook'), ('handout', 'handout')], max_length=200, null=True, verbose_name='leasson artibute'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='class_level',
            field=models.CharField(blank=True, choices=[('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('BECE', 'BECE'), ('Common entrance', 'Common entrance')], default='', max_length=200, null=True, verbose_name='leasson class'),
        ),
    ]
