# Generated by Django 5.1.3 on 2025-05-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0005_lesson_attribute_alter_lesson_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='course name assepts'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='add_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='eduklinikapp.staff'),
        ),
    ]
