# Generated by Django 5.1.3 on 2025-05-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0006_course_course_name_lesson_add_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='course price amount'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='course price amount'),
        ),
    ]
