# Generated by Django 5.1.3 on 2025-05-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0007_course_price_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='drive_link',
            field=models.URLField(blank=True, max_length=1000000, null=True, verbose_name='drive link of the course'),
        ),
    ]
