# Generated by Django 5.1.3 on 2025-05-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0008_course_drive_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=0, verbose_name='user age '),
        ),
    ]
