# Generated by Django 5.1.3 on 2025-05-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0009_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='c_notification',
            name='linked_to',
            field=models.URLField(blank=True, null=True, verbose_name='place or page where the notification will direct to'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Admin', 'Admin'), ('staff', 'Staff'), ('Parent', 'Parent')], default='General', max_length=200, null=True, verbose_name='the account type'),
        ),
        migrations.AlterField(
            model_name='tech_msg',
            name='is_linked',
            field=models.BooleanField(default=False, verbose_name='if teacher is linked already'),
        ),
    ]
