# Generated by Django 5.1.3 on 2025-05-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduklinikapp', '0011_transaction_amount_transaction_email_quize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tran_holder',
        ),
    ]
